import { results } from './Text.stories';

test('basic construction', () => {
  expect(results.basic.outerHTML).toMatchInlineSnapshot(
    `"<div style=\\"min-width: 100px; min-height: 200px; width: 200px; height: 300px; max-width: 300px; max-height: 400px; border: 1px solid black; resize: both; overflow: hidden;\\"><svg viewBox=\\"0 0 100 100\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\"><text fill=\\"undefined\\" opacity=\\"0.5\\" stroke=\\"blue\\" stroke-width=\\"0.5\\" x=\\"10\\" y=\\"10\\" font-size=\\"10px\\" font-family=\\"cursive\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">Hi 10</text><text fill=\\"undefined\\" opacity=\\"0.5\\" stroke=\\"blue\\" stroke-width=\\"0.5\\" x=\\"10\\" y=\\"50\\" font-size=\\"20px\\" font-family=\\"sans-serif\\" alignment-baseline=\\"baseline\\" font-weight=\\"bold\\">There 50</text></svg></div>"`
  );
});

test('minimal construction', () => {
  expect(results.defaults.outerHTML).toMatchInlineSnapshot(
    `"<div style=\\"min-width: 200px; min-height: 200px; width: 300px; height: 300px; max-width: 400px; max-height: 400px; border: 1px solid black; resize: both; overflow: hidden;\\"><svg viewBox=\\"0 0 100 100\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\"><text fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"10\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">yo</text><text fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"50\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">yo</text></svg></div>"`
  );
});

test('text anchor', () => {
  expect(results.textAnchor.outerHTML).toMatchInlineSnapshot(
    `"<div style=\\"min-width: 100px; min-height: 200px; width: 200px; height: 300px; max-width: 300px; max-height: 400px; border: 1px solid black; resize: both; overflow: hidden;\\"><svg viewBox=\\"0 0 100 100\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\"><line x1=\\"50\\" y1=\\"0\\" x2=\\"50\\" y2=\\"100\\" stroke=\\"grey\\"></line><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"50\\" y=\\"30\\" font-size=\\"16px\\" text-anchor=\\"start\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">start</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"50\\" y=\\"60\\" font-size=\\"16px\\" text-anchor=\\"middle\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">middle</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"50\\" y=\\"90\\" font-size=\\"16px\\" text-anchor=\\"end\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">end</text></svg></div>"`
  );
});

test('text anchor', () => {
  expect(results.alignmentBaseline.outerHTML).toMatchInlineSnapshot(
    `"<div style=\\"min-width: 100px; min-height: 200px; width: 200px; height: 300px; max-width: 300px; max-height: 400px; border: 1px solid black; resize: both; overflow: hidden;\\"><svg viewBox=\\"0 0 130 320\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\"><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"40\\" x2=\\"130\\" y2=\\"40\\"></line><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"80\\" x2=\\"130\\" y2=\\"80\\"></line><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"120\\" x2=\\"130\\" y2=\\"120\\"></line><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"160\\" x2=\\"130\\" y2=\\"160\\"></line><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"200\\" x2=\\"130\\" y2=\\"200\\"></line><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"240\\" x2=\\"130\\" y2=\\"240\\"></line><line fill=\\"grey\\" stroke=\\"black\\" stroke-width=\\"1\\" x1=\\"0\\" y1=\\"280\\" x2=\\"130\\" y2=\\"280\\"></line><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"40\\" font-size=\\"16px\\" alignment-baseline=\\"baseline\\" font-weight=\\"normal\\">baseline AaGg</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"80\\" font-size=\\"16px\\" alignment-baseline=\\"middle\\" font-weight=\\"normal\\">middle AaGg</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"120\\" font-size=\\"16px\\" alignment-baseline=\\"text-top\\" font-weight=\\"normal\\">text-top AaGg</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"160\\" font-size=\\"16px\\" alignment-baseline=\\"hanging\\" font-weight=\\"normal\\">hanging AaGg</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"200\\" font-size=\\"16px\\" alignment-baseline=\\"top\\" font-weight=\\"normal\\">top AaGg</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"240\\" font-size=\\"16px\\" alignment-baseline=\\"bottom\\" font-weight=\\"normal\\">bottom AaGg</text><text fill=\\"black\\" stroke=\\"none\\" stroke-width=\\"1\\" x=\\"10\\" y=\\"280\\" font-size=\\"16px\\" alignment-baseline=\\"central\\" font-weight=\\"normal\\">central AaGg</text></svg></div>"`
  );
});
